apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  #annotations:
  #  logger: only-for-horusd-nifi-logger-only
  name: logger-policy
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 103
      min: 3
    rule: MustRunAs
  volumes:
  - '*'