apiVersion: v1
kind: ConfigMap
metadata:
  name: minifi-configmap
  namespace: logging
data:
  bootstrap.conf: |
    #
    # Licensed to the Apache Software Foundation (ASF) under one or more
    # contributor license agreements.  See the NOTICE file distributed with
    # this work for additional information regarding copyright ownership.
    # The ASF licenses this file to You under the Apache License, Version 2.0
    # (the "License"); you may not use this file except in compliance with
    # the License.  You may obtain a copy of the License at
    #
    #   http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    #
    
    # Java command to use when running MiNiFi
    java=java
    
    # Username to use when running MiNiFi. This value will be ignored on Windows.
    run.as=
    
    # Configure where MiNiFi's lib and conf directories live
    # When running as a Windows service set full paths instead of relative paths
    lib.dir=./lib
    conf.dir=./conf
    
    # How long to wait after telling MiNiFi to shutdown before explicitly killing the Process
    graceful.shutdown.seconds=20
    
    # The location for the configuration file
    # When running as a Windows service use the full path to the file
    nifi.minifi.config=./conf/config.yml
    
    # Notifiers to use for the associated agent, comma separated list of class names
    #nifi.minifi.notifier.ingestors=org.apache.nifi.minifi.bootstrap.configuration.ingestors.FileChangeIngestor
    #nifi.minifi.notifier.ingestors=org.apache.nifi.minifi.bootstrap.configuration.ingestors.RestChangeIngestor
    #nifi.minifi.notifier.ingestors=org.apache.nifi.minifi.bootstrap.configuration.ingestors.PullHttpChangeIngestor
    
    # File change notifier configuration
    
    # Path of the file to monitor for changes.  When these occur, the FileChangeNotifier, if configured, will begin the configuration reloading process
    #nifi.minifi.notifier.ingestors.file.config.path=
    # How frequently the file specified by 'nifi.minifi.notifier.file.config.path' should be evaluated for changes.
    #nifi.minifi.notifier.ingestors.file.polling.period.seconds=5
    
    # Rest change notifier configuration
    
    # Port on which the Jetty server will bind to, keep commented for a random open port
    #nifi.minifi.notifier.ingestors.receive.http.port=8338
    
    #Pull HTTP change notifier configuration
    
    # Hostname on which to pull configurations from
    #nifi.minifi.notifier.ingestors.pull.http.hostname=localhost
    # Port on which to pull configurations from
    #nifi.minifi.notifier.ingestors.pull.http.port=4567
    # Path to pull configurations from
    #nifi.minifi.notifier.ingestors.pull.http.path=/c2/config
    # Query string to pull configurations with
    #nifi.minifi.notifier.ingestors.pull.http.query=class=raspi3
    # Period on which to pull configurations from, defaults to 5 minutes if commented out
    #nifi.minifi.notifier.ingestors.pull.http.period.ms=300000
    
    # Periodic Status Reporters to use for the associated agent, comma separated list of class names
    #nifi.minifi.status.reporter.components=org.apache.nifi.minifi.bootstrap.status.reporters.StatusLogger
    
    # Periodic Status Logger configuration
    
    # The FlowStatus query to submit to the MiNiFi instance
    #nifi.minifi.status.reporter.log.query=instance:health,bulletins
    # The log level at which the status will be logged
    #nifi.minifi.status.reporter.log.level=INFO
    # The period (in milliseconds) at which to log the status
    #nifi.minifi.status.reporter.log.period=60000
    
    # Disable JSR 199 so that we can use JSP's without running a JDK
    java.arg.1=-Dorg.apache.jasper.compiler.disablejsr199=true
    
    # JVM memory settings
    java.arg.2=-Xms256m
    java.arg.3=-Xmx256m
    
    # Enable Remote Debugging
    #java.arg.debug=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    
    java.arg.4=-Djava.net.preferIPv4Stack=true
    
    # allowRestrictedHeaders is required for Cluster/Node communications to work properly
    java.arg.5=-Dsun.net.http.allowRestrictedHeaders=true
    java.arg.6=-Djava.protocol.handler.pkgs=sun.net.www.protocol
    
    # Sets the provider of SecureRandom to /dev/urandom to prevent blocking on VMs
    java.arg.7=-Djava.security.egd=file:/dev/urandom
    
    
    # The G1GC is still considered experimental but has proven to be very advantageous in providing great
    # performance without significant "stop-the-world" delays.
    #java.arg.13=-XX:+UseG1GC
    
    #Set headless mode by default
    java.arg.14=-Djava.awt.headless=true
    
  config.yml: |
    # Licensed to the Apache Software Foundation (ASF) under one or more
    # contributor license agreements.  See the NOTICE file distributed with
    # this work for additional information regarding copyright ownership.
    # The ASF licenses this file to You under the Apache License, Version 2.0
    # (the \"License\"); you may not use this file except in compliance with
    # the License.  You may obtain a copy of the License at
    #
    #     http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an \"AS IS\" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    
    MiNiFi Config Version: 3
    Flow Controller:
      name: MiNiFi Flow
      comment: ''
    Core Properties:
      flow controller graceful shutdown period: 10 sec
      flow service write delay interval: 500 ms
      administrative yield duration: 30 sec
      bored yield duration: 10 millis
      max concurrent threads: 1
    FlowFile Repository:
      partitions: 256
      checkpoint interval: 2 mins
      always sync: false
      Swap:
        threshold: 20000
        in period: 5 sec
        in threads: 1
        out period: 5 sec
        out threads: 4
    Content Repository:
      content claim max appendable size: 10 MB
      content claim max flow files: 100
      always sync: false
    Provenance Repository:
      provenance rollover time: 1 min
    Component Status Repository:
      buffer size: 1440
      snapshot frequency: 1 min
    Security Properties:
      keystore: ''
      keystore type: ''
      keystore password: ''
      key password: ''
      truststore: ''
      truststore type: ''
      truststore password: ''
      ssl protocol: ''
      Sensitive Props:
        key: ''
        algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
        provider: BC
    Processors: []
    Process Groups: []
    Funnels: []
    Connections: []
    Remote Process Groups: []
    NiFi Properties Overrides: {}
