apiVersion: v1
kind: ServiceAccount
metadata:
  name: horusd
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: horusd-role
  namespace: logging
rules: 
  - apiGroups:
    - ""
    - policy
    - extensions
    resourceNames:
    - logger-policy
    resources: 
    - podsecuritypolicies
    verbs: 
    - get
    - list
    - watch
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: horusd-rolebinding-psp
subjects: 
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:logging
roleRef: 
  kind: Role
  name: horusd-role
  apiGroup: ""